### ISSUE TITLE
1964 0.8.5

### ISSUE THREAD

**Issue by cxd4** [LegendOfDragoon/1964-X#1]
Have you considered doing a fork of version 0.8.5 instead of 1.1?

I haven't had a 1964-compatible platform for over a year, but I don't remember 1.1 really fixing anything that didn't work on 1964 0.8.5 already.  I think it fixed long-broken stuff that was wrong with 0.9.9.

I also wouldn't want to put time into a Unix fork of something that's heavily drowned with C++.  0.8.5 as far as I know is the final version of 1964 written in C.  Anything past that was to have a faster dynamic recompiler...fine and well, but I'd rather work on the version with fewer bugs in the interpreter.

**Comment by theboy181** [comment]
why 8.5 ? this due to the timing being better as well?

**Comment by cxd4** [comment]
Just different reasons really.

It's not a particular "issue", but it's a good enough idea that I would rather do that.  Forking 1.1 will be popular enough to anyone else contributing to 1964.

**Comment by LegendOfDragoon** [comment]
That's not something I've considered in recent times, but it does now sound like a nice idea. Seems like 1964 0.85 does have some advantages over 1.1.

One of the main reasons I started using 1.1 instead was because I think it has better compatibility. Its UI is also more polished and that Ultrafast fork fixed some of the GUI issues.

Here's an issue in Smash Bros with 1964 0.85 
![image](https://cloud.githubusercontent.com/assets/10492645/22866928/a99d9eae-f132-11e6-8277-a6d97c14ed90.png)

Now that I have more experience, I don't mind attempting to tackle some of these issues. If you're interested in improving 1964 0.85, then I will gladly work on that.

**Comment by cxd4** [comment]
The last I ran 0.8.5, I could tell the GUI was sort of Win95-themed.  I didn't really care though.  The more sophisticated the GUI the more crap I have to work around in a fork; I'd rather be able to concentrate and let someone else PR stuff like that in at the end.

I know 1.1 was more compatible than 0.9.9, but I didn't remember it being the most compatible version.  Did that fix the issue in _Banjo-Tooie_ with the fire eggs not triggering that switch to the pine grove from the plateau?  0.9.9 FAQ said the only fix was to use 0.8.5.

Anyway, it's all thoughts for the time being since I'm not a hermit anymore and won't be able to start porting 0.8.5 for a time.

**Comment by LegendOfDragoon** [comment]
I'll consider forking 0.8.5. I don't have that much free time these days either. Perhaps when I lose interest in working on gfx plugins, I'll go back to tweaking emulator cores.

I haven't really tested Tooie much, so not sure if it works properly on 1.1.

**Comment by cxd4** [comment]
I'll just start a new game and give you a save file for you to plug in and test.  The only way to reproduce it is to make it up to the Plateau region and learn how to use fire eggs, without having entered Pine Grove yet.  I'll give you a save when I get time.

If you don't fork it that's fine.  I'll probably end up forking it myself.  Use whatever time you think is time better spent; I was planning to put a Git history of all the 1964 releases up to 0.8.5 to show diff's for older versions up until then to initialize the repo that way.

**Comment by weinerschnitzel** [comment]
Git history for 1964 would be awesome!

I do recall some minor improvements, but 1964 1.1 should pretty much be 0.9.9. Schibo accidentally released an experimental recompiler as 1.0, then took it down and released 1.1 with what i assume would be 0.9.9's dynarec. 

There was the bone glitch that went away in 1.1 because of timing, but that wasnt really a solution.

Ive spent awhile staring at both 0.8.5 and 1.1. Id love to get involved tracking the changes. 

Also why not start earlier than 0.8.5?

**Comment by cxd4** [comment]
History would start not at 0.8.5 but at the beginning.

It would end at 0.8.5, and any fork I do will be based on that version.

**Comment by LegendOfDragoon** [comment]
What versions are open source? All I know of is 0.8.5 and 1.1.

I definitely do want to work on a core, either improving existing ones or writing my own. It's just that there's other things I want to do as well, like improving gfx plugins. It's hard for me to decide which one to do first. I like 1964, but there were too many issues, so I didn't feel like investing too much into it. I just like to tweak a few things here and there.

I'm not sure how much effort I'd be willing to put into 0.8.5. It kind of depends on how difficult it is to track down some of these bugs. Certainly I don't mind making some improvements like I did with 1.1. Things like adding the option in GUI to select which RSP, is trivial.

**Comment by weinerschnitzel** [comment]
There are lots of pre 0.8.5 releases with source code on SF. I like the idea of tracking the history to 0.8.5. There may be some useful speed hacks i could figure in for xbox builds.

I wouldnt mind back porting any fixes to your 0.8.5 fork should it include full history.

**Comment by weinerschnitzel** [comment]
Should also note that SSB's Race to the Finish is also broken in 0.8.5. Might be related to the issue noted by @LegendofDragoon above.

**Comment by cxd4** [comment]
But anything after 0.8.5 I will not be committing version upload tracking for.  Anything after 0.8.5 is stuff rewritten all in C++, which is just going to have all the files renamed, all the files totally changed, and, well, quite frankly, all the files changed to sloppier and lazier code that isn't that useful to track.  So doing `git commit` for everything up to 0.8.5 would be significant; anything after would be a bunch of junk like files renamed to .cpp.

>I'm not sure how much effort I'd be willing to put into 0.8.5.

It's hardly any benefit for me to fork 1964 beyond getting a 64-bit Linux port working on my machine.

The objective is not to fix trivial bugs that do not stop me from testing plugins on it, without necessarily having to run everything under Mupen64.  It's just to get the emulator to work.  I'm not seeking to improve it with whatever theboy181's drooling about.

>It kind of depends on how difficult it is to track down some of these bugs.

I have found that there are more bugs in 0.9.9, 1.0 and 1.1 that aren't in 0.8.5 than the other way around anyway.  Many demos seriously do not work right or even boot in post-0.8.5 versions of 1964.

>Things like adding the option in GUI to select which RSP, is trivial.

IIRC 1964 0.8.5 already had a checkbox to use a rsp.dll file, so we're already able to change that.

**Comment by cxd4** [comment]
Dunno if this link works or not, but...

https://dl.dropboxusercontent.com/u/16494013/Banjo-Tooie%20(U)%20%5B!%5D.eep

Follow the behavior in this video from 8:20 to 8:40.
https://youtu.be/Q5IxTWKExRc?t=8m20s

Again, the 1964 0.9.9 FAQ says this can't be fixed in the settings.  It suggests downgrading to 0.8.5 as the only solution.  @LegendOfDragoon feel free to follow the action in that video with the save file I uploaded (when the switch has never been hit yet).  If nothing happens when you shoot the switch with a fire arrow, then it has the same bug on 1964 1.1 as with 0.9.9.

**Comment by weinerschnitzel** [comment]
Iirc alot of the cpp changes were really just file renames. Admitedly, it's been years since I looked at them in UltraCompare. Nonetheless, I can still compare those on my own and we could verify improvements later by PRing them to your fork with git history.

**Comment by cxd4** [comment]
If file renames are the only change then that just further takes away from the purpose of tracking them.

It's the way Project64 1.7 transitioned, too.  At first everything was just renaming from .c to .cpp.  Guess what came afterwards? :smile: A retarded oriental-faced GitHub emote representing what happens when you rewrite things in C++.

**Comment by weinerschnitzel** [comment]
We should be able to identify things worth backporting to 0.8.5.

FBInfo and AutoCF as well as the SSB fixes should be worth while.

Did that RSP timing setting ever do anything?

**Comment by LegendOfDragoon** [comment]
Alright, I'll try testing Tooie this week. Cool, maybe I will look at those older sources.

>IIRC 1964 0.8.5 already had a checkbox to use a rsp.dll file, so we're already able to change that.

Yea. I just prefer having a dropdownlist so that I can use different RSP plugins without having to rename dlls.

>If you don't fork it that's fine. I'll probably end up forking it myself.

It's probably better if you make the fork. You're more likely to make bigger changes than I am and idk when I'll get started either.

>Iirc alot of the cpp changes were really just file renames.

Quite a bit of the code has actually been changed. Especially the recompiler.

>Did that RSP timing setting ever do anything?

Not sure if it actually was beneficial or not.

I look forward to examining 0.8.5's source again.

**Comment by weinerschnitzel** [comment]
Awesome. I look forward to analyzing the changes from 0 8.5 for maximum benefit.

**Comment by cxd4** [comment]
A primary thing is identifying regressions, which is part of why I would commit the history up to 0.8.5.  Adding commits for future versions after 0.8.5 doesn't *show* regressions, just changes to pick through for what fixes things like SSB.

It can go in some separate branch probably.  I would rather keep post-0.8.5 log commits out of the master branch and keep things clean.  Wanting to see changes after 0.8.5 does not justify forking versions after 0.8.5; the master branch should be kept clean of the regressions introduced after that version as well as the C++.

**Comment by cxd4** [comment]
>>What versions are open source? All I know of is 0.8.5 and 1.1.

>There are lots of pre 0.8.5 releases with source code on SF.

@weinerschnitzel What is this meant to be in reference to?  The only source release of 1964 on SF is just 0.8.5; I think you'd better check that SF.

**Comment by weinerschnitzel** [comment]
Yep, I was wrong on that one. I could have sworn there were other versions up there. Woops.

**Comment by cxd4** [comment]
Historically it seems that there were...schibo has done a lot of takedowns of sources for older versions due to the drama of his code being stolen it seems.  Basically every version has been open-source, but he's been quick to delete the source for older versions when at least one newer version is available.

**Comment by cxd4** [comment]
It looks like 0.9.9 is the only version he's never open-sourced anyway.

1.1 and all versions older than or equal to 0.8.5 had source available.  The only trick is plucking them.

**Comment by cxd4** [comment]
I managed to improvise for a few hours.
https://github.com/cxd4/1986/commits/master

Source code to various legacy versions is available scarcely if you'll cross a ton of domain mirrors.

I hit a bump with finding 0.0.7, though.  Is anyone able to find that?

If not, then no big deal.  Guess the show must go on; I'll have to skip it.  Oldest source I can find after 0.0.6 is 0.4.9.  I really need a break anyway.  Committing the files in each version package sounds like icing on the cake until schibo decides to rename files **and** change their contents.  Then I have to do `git mv` on the low level to rename the file using Git and then paste the contents of the files over, or else I lose tracking of that file and the rename causes it to commit as a file deletion plus a file creation when it's really just a file being renamed.

Just one more reason not to bother with those .cpp files in 1964 1.1.  Anyway I need a break now.

**Comment by Azimer** [comment]
It's going to be rough finding something from 16 years ago when the author doesn't maintain their own webpage.  I wonder if the internet archive can help.

**Comment by cxd4** [comment]
Hah, yeah that's what I've been using.

Wayback Machine on zophar.net, 1964emu.emulation64.com, emutalk.net (back when attachments used to work...), ngemu.com, emuhq.com/1964, sourceforge.net, emulation64.com, ... only thing I forgot to try I guess was Dextrose.

Froze my computer today doing a search for all file names on the Internet archive containing "1964" in emutalk's wayback history.  Froze my operating system to the point where my wi-fi stopped responding and I had to reboot.

**Comment by cxd4** [comment]
Finally glad to be done with that messy history.

Everything obtainable from 1964 0.0.1 to 0.8.5 is committed into the source tracker at my repo.

@weinerschnitzel do you still want me to commit 1964 1.1 in to the repo under a branch separate from master?  If you look at the existing diff's, I'm not sure you'll find it pleasant reading.  I don't think 1.1 would be any better, but if you still think it would help I will go ahead to attempt it.

@LegendOfDragoon:  Found an old little gem here:  https://github.com/cxd4/1986/blob/225d7d33553b49d5a496f9fbcbb19357061f3152/dynaRec/1964_Recompiler.pdf .  Might be a fun read for you.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon: Found an old little gem here:

I've seen that before, but thanks for mentioning it here. I enjoyed reading it again :smile: .

**Comment by weinerschnitzel** [comment]
@cxd4 You don't have to go through it if you don't want to, but it would be convenient to have it on github. A separate branch is a good idea. 

Nice work tracking the versions. Its easy enough to look at on the go.

**Comment by cxd4** [comment]
https://github.com/cxd4/1986/commit/61811f21de72d97733a1b6b22705b709ddd1d2fa

Good luck. :P 

Somebody must have really found that 1964_Recompiler.pdf file interesting.  I don't just mean LegendOfDragoon; that file was supplied with 1964 0.6.0 and deleted from their source repository before 0.6.4 source had come out.  So somebody must have mirrored that thing like crazy during the short time that file was officially available.
